// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisJur.Models;

#nullable disable

namespace SisJur.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250928230902_inical")]
    partial class inical
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SisJur.Models.Advogado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("areaid")
                        .HasColumnType("int");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.HasIndex("areaid");

                    b.ToTable("advogados");
                });

            modelBuilder.Entity("SisJur.Models.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id");

                    b.ToTable("areas");
                });

            modelBuilder.Entity("SisJur.Models.Processo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("entrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("tipoprocessoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tipoprocessoid");

                    b.ToTable("processos");
                });

            modelBuilder.Entity("SisJur.Models.TipoProcesso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id");

                    b.ToTable("tipoprocessos");
                });

            modelBuilder.Entity("SisJur.Models.Vara", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("advogadoid")
                        .HasColumnType("int");

                    b.Property<string>("juiz")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("processoid")
                        .HasColumnType("int");

                    b.Property<float>("valorcausa")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("advogadoid");

                    b.HasIndex("processoid");

                    b.ToTable("varas");
                });

            modelBuilder.Entity("SisJur.Models.Advogado", b =>
                {
                    b.HasOne("SisJur.Models.Area", "area")
                        .WithMany("advogados")
                        .HasForeignKey("areaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("area");
                });

            modelBuilder.Entity("SisJur.Models.Processo", b =>
                {
                    b.HasOne("SisJur.Models.TipoProcesso", "tipoprocesso")
                        .WithMany("listaProcessos")
                        .HasForeignKey("tipoprocessoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoprocesso");
                });

            modelBuilder.Entity("SisJur.Models.Vara", b =>
                {
                    b.HasOne("SisJur.Models.Advogado", "Advogado")
                        .WithMany()
                        .HasForeignKey("advogadoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisJur.Models.Processo", "Processo")
                        .WithMany()
                        .HasForeignKey("processoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advogado");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("SisJur.Models.Area", b =>
                {
                    b.Navigation("advogados");
                });

            modelBuilder.Entity("SisJur.Models.TipoProcesso", b =>
                {
                    b.Navigation("listaProcessos");
                });
#pragma warning restore 612, 618
        }
    }
}
